/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inventory4ia17.View;

import com.mycompany.inventory4ia17.Controller.ControllerInv;
import com.mycompany.inventory4ia17.Model.Model;
import com.mycompany.inventory4ia17.Model.ModelTabel;
import com.mycompany.inventory4ia17.Service.ServiceInv;
import java.util.List;

/**
 *
 * @author Platina Setia Budi
 */
public class View extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(View.class.getName());

    private ControllerInv controller;

    /**
     * Creates new form View
     */
    public View(ControllerInv controller) {
        this.controller = controller;
        initComponents();
        loadTable();
    }

    private View() {
        throw new UnsupportedOperationException("Not Supported yet.");

    }

    public void loadTable() {
        List<Model> listInv = controller.getAllInv();
        ModelTabel tablemodel = new ModelTabel(listInv);
        dataTable.setModel(tablemodel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addinventory = new javax.swing.JDialog();
        addCode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addName = new javax.swing.JTextField();
        addAmount = new javax.swing.JTextField();
        addLocation = new javax.swing.JTextField();
        addCancel = new javax.swing.JButton();
        addSave = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        editinventory = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        editId = new javax.swing.JTextField();
        editCode = new javax.swing.JTextField();
        editName = new javax.swing.JTextField();
        editAmount = new javax.swing.JTextField();
        editLocation = new javax.swing.JTextField();
        editCancel = new javax.swing.JButton();
        editSave = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        deleteinventory = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        deleteId = new javax.swing.JTextField();
        deleteCode = new javax.swing.JTextField();
        deleteName = new javax.swing.JTextField();
        deleteAmount = new javax.swing.JTextField();
        deleteLocation = new javax.swing.JTextField();
        deleteCancel = new javax.swing.JButton();
        deleteSave = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();

        addinventory.setPreferredSize(new java.awt.Dimension(400, 300));

        addCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        addCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCodeActionPerformed(evt);
            }
        });

        jLabel2.setText("Add Inventory");

        addName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        addName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNameActionPerformed(evt);
            }
        });

        addAmount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        addAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAmountActionPerformed(evt);
            }
        });

        addLocation.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        addCancel.setText("Cancel");
        addCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCancelActionPerformed(evt);
            }
        });

        addSave.setText("Add");
        addSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSaveActionPerformed(evt);
            }
        });

        jLabel3.setText("Kode Barang");

        jLabel4.setText("Nama Barang");

        jLabel5.setText("Jumlah Barang");

        jLabel6.setText("Lokasi");

        javax.swing.GroupLayout addinventoryLayout = new javax.swing.GroupLayout(addinventory.getContentPane());
        addinventory.getContentPane().setLayout(addinventoryLayout);
        addinventoryLayout.setHorizontalGroup(
            addinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addinventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(addCancel))
                .addGap(18, 18, 18)
                .addGroup(addinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(addinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(addCode, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addSave, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addinventoryLayout.setVerticalGroup(
            addinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addinventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(addinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(addinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(addinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(addinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSave)
                    .addComponent(addCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("Edit Inventory");

        editId.setEnabled(false);
        editId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editIdActionPerformed(evt);
            }
        });

        editCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        editCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCodeActionPerformed(evt);
            }
        });

        editName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        editName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editNameActionPerformed(evt);
            }
        });

        editAmount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        editAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAmountActionPerformed(evt);
            }
        });

        editLocation.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        editCancel.setText("Cancel");
        editCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCancelActionPerformed(evt);
            }
        });

        editSave.setText("Edit");
        editSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSaveActionPerformed(evt);
            }
        });

        jLabel12.setText("Id Barang");

        jLabel8.setText("Kode Barang");

        jLabel9.setText("Nama Barang");

        jLabel10.setText("Jumlah Barang");

        jLabel11.setText("Lokasi");

        javax.swing.GroupLayout editinventoryLayout = new javax.swing.GroupLayout(editinventory.getContentPane());
        editinventory.getContentPane().setLayout(editinventoryLayout);
        editinventoryLayout.setHorizontalGroup(
            editinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editinventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(editCancel)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(editinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editId)
                    .addComponent(jLabel7)
                    .addComponent(editCode, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(editLocation, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(editAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(editName, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(editSave, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(38, 148, Short.MAX_VALUE))
        );
        editinventoryLayout.setVerticalGroup(
            editinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editinventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(editinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(editinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(editinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(editinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(editinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(editinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editSave)
                    .addComponent(editCancel))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel13.setText("Delete Inventory");

        deleteId.setEnabled(false);
        deleteId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteIdActionPerformed(evt);
            }
        });

        deleteCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        deleteCode.setEnabled(false);
        deleteCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCodeActionPerformed(evt);
            }
        });

        deleteName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        deleteName.setEnabled(false);
        deleteName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteNameActionPerformed(evt);
            }
        });

        deleteAmount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        deleteAmount.setEnabled(false);
        deleteAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAmountActionPerformed(evt);
            }
        });

        deleteLocation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        deleteLocation.setEnabled(false);

        deleteCancel.setText("Cancel");
        deleteCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCancelActionPerformed(evt);
            }
        });

        deleteSave.setText("Delete");
        deleteSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSaveActionPerformed(evt);
            }
        });

        jLabel14.setText("Id Barang");

        jLabel15.setText("Kode Barang");

        jLabel16.setText("Nama Barang");

        jLabel17.setText("Jumlah Barang");

        jLabel18.setText("Lokasi");

        javax.swing.GroupLayout deleteinventoryLayout = new javax.swing.GroupLayout(deleteinventory.getContentPane());
        deleteinventory.getContentPane().setLayout(deleteinventoryLayout);
        deleteinventoryLayout.setHorizontalGroup(
            deleteinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteinventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deleteinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(deleteCancel)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(deleteinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteId)
                    .addComponent(jLabel13)
                    .addComponent(deleteCode, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(deleteLocation, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(deleteAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(deleteName, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(deleteSave, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(38, 148, Short.MAX_VALUE))
        );
        deleteinventoryLayout.setVerticalGroup(
            deleteinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteinventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(deleteinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(deleteinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(deleteinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(deleteinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(deleteinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(deleteinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteSave)
                    .addComponent(deleteCancel))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Nama.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Nama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nama.setText("Simple Inventory");

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(dataTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addBtn)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(refreshBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editBtn))
                        .addGap(18, 18, 18)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Nama)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(editBtn)
                    .addComponent(deleteBtn))
                .addGap(18, 18, 18)
                .addComponent(refreshBtn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        addinventory.setSize(400, 300);
        addinventory.setLocationRelativeTo(this);
        addinventory.setModal(true);
        addinventory.setVisible(true);
    }//GEN-LAST:event_addBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        loadTable();

    }//GEN-LAST:event_refreshBtnActionPerformed

    private void addCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCodeActionPerformed

    private void addNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addNameActionPerformed

    private void addCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCancelActionPerformed
        addinventory.setVisible(false);
    }//GEN-LAST:event_addCancelActionPerformed

    private void addSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSaveActionPerformed
        String Code = addCode.getText();
        String Name = addName.getText();
        int Amount = Integer.parseInt(addAmount.getText());
        String Location = addLocation.getText();

        Model inv = new Model(0, Code, Name, Amount, Location);
        controller.addInv(inv);
        loadTable();
        addinventory.setVisible(false);
    }//GEN-LAST:event_addSaveActionPerformed

    private void addAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addAmountActionPerformed

    private void editCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editCodeActionPerformed

    private void editNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editNameActionPerformed

    private void editAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editAmountActionPerformed

    private void editCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCancelActionPerformed
        editinventory.setVisible(false);
    }//GEN-LAST:event_editCancelActionPerformed

    private void editSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSaveActionPerformed
        int id = Integer.parseInt(editId.getText());
        String Code = editCode.getText();
        String Name = editName.getText();
        int Amount = Integer.parseInt(editAmount.getText());
        String Location = editLocation.getText();

        Model inv = new Model(id, Code, Name, Amount, Location);
        controller.editInv(inv);
        loadTable();
        editinventory.setVisible(false);

    }//GEN-LAST:event_editSaveActionPerformed

    private void editIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editIdActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        int row = dataTable.getSelectedRow();
        if (row != -1) {
            editId.setText(dataTable.getValueAt(row, 0).toString());
            editCode.setText(dataTable.getValueAt(row, 1).toString());
            editName.setText(dataTable.getValueAt(row, 2).toString());
            editAmount.setText(dataTable.getValueAt(row, 3).toString());
            editLocation.setText(dataTable.getValueAt(row, 4).toString());
            editinventory.setSize(400, 300);
            editinventory.setLocationRelativeTo(this);
            editinventory.setModal(true);
            editinventory.setVisible(true);
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int row = dataTable.getSelectedRow();
        if (row != -1) {
            deleteId.setText(dataTable.getValueAt(row, 0).toString());
            deleteCode.setText(dataTable.getValueAt(row, 1).toString());
            deleteName.setText(dataTable.getValueAt(row, 2).toString());
            deleteAmount.setText(dataTable.getValueAt(row, 3).toString());
            deleteLocation.setText(dataTable.getValueAt(row, 4).toString());
            deleteinventory.setSize(400, 300);
            deleteinventory.setLocationRelativeTo(this);
            deleteinventory.setModal(true);
            deleteinventory.setVisible(true);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void deleteIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteIdActionPerformed

    private void deleteCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteCodeActionPerformed

    private void deleteNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteNameActionPerformed

    private void deleteAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteAmountActionPerformed

    private void deleteCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCancelActionPerformed
        deleteinventory.setVisible(false);
    }//GEN-LAST:event_deleteCancelActionPerformed

    private void deleteSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSaveActionPerformed
        int id = Integer.parseInt(deleteId.getText());
        String Code = deleteCode.getText();
        String Name = deleteName.getText();
        int Amount = Integer.parseInt(deleteAmount.getText());
        String Location = deleteLocation.getText();

        Model inv = new Model(id, Code, Name, Amount, Location);
        controller.deleteInv(id);
        loadTable();
        deleteinventory.setVisible(false);
    }//GEN-LAST:event_deleteSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new View().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nama;
    private javax.swing.JTextField addAmount;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton addCancel;
    private javax.swing.JTextField addCode;
    private javax.swing.JTextField addLocation;
    private javax.swing.JTextField addName;
    private javax.swing.JButton addSave;
    private javax.swing.JDialog addinventory;
    private javax.swing.JTable dataTable;
    private javax.swing.JTextField deleteAmount;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton deleteCancel;
    private javax.swing.JTextField deleteCode;
    private javax.swing.JTextField deleteId;
    private javax.swing.JTextField deleteLocation;
    private javax.swing.JTextField deleteName;
    private javax.swing.JButton deleteSave;
    private javax.swing.JDialog deleteinventory;
    private javax.swing.JTextField editAmount;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton editCancel;
    private javax.swing.JTextField editCode;
    private javax.swing.JTextField editId;
    private javax.swing.JTextField editLocation;
    private javax.swing.JTextField editName;
    private javax.swing.JButton editSave;
    private javax.swing.JDialog editinventory;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refreshBtn;
    // End of variables declaration//GEN-END:variables
}
